name: node-ci

on:
  push:
    branches: [main]        # se ejecutará en cada push a main
  pull_request:
    branches: [main]        # y en cada PR contra main
  workflow_dispatch:        # <── habilita botón “Run workflow”










